[build-system]
requires = ["setuptools>=64.0", "wheel", "platformdirs"]
build-backend = "setuptools.build_meta"

[project]
name = "ucd"
version = "0.1"
authors = [{name = "SIL WSTech", email = "fonts@sil.org"}]
readme = "README.md"
license = { text = "MIT" }
description = "Unicode UCD wrapper module"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",   # match your actual license
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Text Processing :: Linguistic",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
requires-python = ">=3.9"
#dynamic = ["version"]
dependencies = ["platformdirs"]

# [project.optional-dependencies]
# dev = [ ]

[project.urls]
Home-Page = "https://github.com/silnrsi/python-ucd"

# [tool.setuptools_scm]
[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
ucd = ["data/ucdata_v*.pickle.bz2"]

#[tool.setuptools.data-files]
#"" = ["tests/*.usfm"]

#[tool.setuptools.dynamic]
#version = {attr = "usfmtc.version"}

#[tool.setuptools]
#packages = ["usfmtc"]

[tool.bdist_wheel]
universal = true

[project.scripts]
ucdinfo = "ucd.ucd:main"
